# Generated by Django 4.2.28 on 2026-02-28
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0120_issueview_archived_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="IssueTypeProperty",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issue_type_properties",
                        to="db.workspace",
                    ),
                ),
                (
                    "issue_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="properties",
                        to="db.issuetype",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("key", models.SlugField(max_length=100)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("rich_text", "Rich Text"),
                            ("url", "URL"),
                            ("enum", "Enum"),
                            ("float", "Float"),
                            ("integer", "Integer"),
                            ("boolean", "Boolean"),
                            ("checklist", "Checklist"),
                            ("array_user_ids", "User IDs"),
                            ("currency", "Currency"),
                            ("tags", "Tags"),
                            ("threaded_list", "Threaded List"),
                            ("timestamped_text", "Timestamped Text"),
                            ("json", "JSON"),
                        ],
                        max_length=30,
                    ),
                ),
                ("is_required", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.FloatField(default=65535)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("maps_to_builtin", models.CharField(blank=True, default="", max_length=50)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("data", "Data"),
                            ("tracking", "Tracking"),
                            ("criteria", "Criteria"),
                            ("governance", "Governance"),
                            ("hitl", "HITL"),
                        ],
                        default="data",
                        max_length=30,
                    ),
                ),
            ],
            options={
                "verbose_name": "Issue Type Property",
                "verbose_name_plural": "Issue Type Properties",
                "db_table": "issue_type_properties",
                "ordering": ("sort_order", "created_at"),
            },
        ),
        migrations.AddConstraint(
            model_name="issuetypeproperty",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("issue_type", "key"),
                name="issue_type_property_unique_type_key_when_not_deleted",
            ),
        ),
        migrations.CreateModel(
            name="IssuePropertyValue",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_values",
                        to="db.issue",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="db.issuetypeproperty",
                    ),
                ),
                ("value_json", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Issue Property Value",
                "verbose_name_plural": "Issue Property Values",
                "db_table": "issue_property_values",
            },
        ),
        migrations.AddConstraint(
            model_name="issuepropertyvalue",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("issue", "property"),
                name="issue_property_value_unique_issue_property_when_not_deleted",
            ),
        ),
        migrations.AddIndex(
            model_name="issuetypeproperty",
            index=models.Index(fields=["issue_type", "is_active"], name="idx_itp_type_active"),
        ),
        migrations.AddIndex(
            model_name="issuepropertyvalue",
            index=models.Index(fields=["issue"], name="idx_ipv_issue"),
        ),
    ]
