# Generated by Django 4.2.28 on 2026-02-28
from django.db import migrations


# Property definitions per issue type (by name).
# Each entry: (key, name, field_type, category, is_required, config, sort_order)
PROPERTY_DEFINITIONS = {
    "Epic": [
        ("strategic_theme", "Strategic Theme", "enum", "data", True, {"options": ["Growth", "Retention", "Compliance", "Infrastructure", "Innovation"]}, 100),
        ("roi", "Target ROI", "currency", "data", False, {"currency": "USD"}, 200),
        ("stakeholders", "Stakeholders", "array_user_ids", "data", False, {}, 300),
        ("risks", "Risks", "rich_text", "data", False, {}, 400),
        ("decision_log", "Decision Log", "rich_text", "tracking", False, {}, 500),
        ("success_criteria", "Success Criteria", "checklist", "criteria", True, {}, 600),
        ("agent_orchestration_strategy", "Agent Orchestration Strategy", "rich_text", "governance", False, {}, 700),
        ("hitl_role_gate", "HITL Role Gate", "text", "hitl", True, {"default": "Product_Executive: Approves ROI and Strategic Alignment."}, 800),
    ],
    "Feature": [
        ("design_link", "Design Link", "url", "data", False, {}, 100),
        ("stack", "Stack", "tags", "data", False, {}, 200),
        ("depends_on", "Depends On", "url", "data", False, {}, 300),
        ("target_release", "Target Release", "text", "data", False, {}, 400),
        ("technical_constraints", "Technical Constraints", "rich_text", "tracking", False, {}, 500),
        ("open_questions", "Open Questions", "threaded_list", "tracking", False, {}, 600),
        ("dod_checklist", "Definition of Done", "checklist", "criteria", True, {}, 700),
        ("tool_set_permission", "Tool Set Permission", "tags", "governance", False, {}, 800),
        ("hitl_role_gate", "HITL Role Gate", "text", "hitl", True, {"default": "Lead_Architect: Approves Schema and Tech Constraints."}, 900),
    ],
    "User Story": [
        ("persona", "Persona", "text", "data", False, {}, 100),
        ("qa_thread", "Q&A Thread", "threaded_list", "tracking", False, {}, 200),
        ("pivot_notes", "Pivot Notes", "timestamped_text", "tracking", False, {}, 300),
        ("acceptance_criteria", "Acceptance Criteria", "checklist", "criteria", True, {}, 400),
        ("prompt_template_id", "Prompt Template ID", "text", "governance", False, {}, 500),
        ("hitl_role_gate", "HITL Role Gate", "text", "hitl", True, {"default": "Product_Owner: Approves AC and Business Value."}, 600),
    ],
    "Task": [
        ("est_hours", "Estimated Hours", "float", "data", False, {"min": 0, "step": 0.5}, 100),
        ("approach", "Approach", "rich_text", "data", False, {}, 200),
        ("pr_url", "PR URL", "url", "data", False, {}, 300),
        ("blocker_log", "Blocker Log", "rich_text", "tracking", False, {"has_boolean_flag": True}, 400),
        ("review_notes", "Review Notes", "rich_text", "tracking", False, {}, 500),
        ("test_criteria", "Test Criteria", "checklist", "criteria", True, {}, 600),
        ("reasoning_trace", "Reasoning Trace", "json", "governance", False, {}, 700),
        ("hitl_role_gate", "HITL Role Gate", "text", "hitl", True, {"default": "Senior_Dev: Approves Code PR and Technical Logic."}, 800),
    ],
    "Sub-task": [
        ("sub_checklist", "Checklist", "checklist", "data", False, {}, 100),
        ("work_log", "Work Log", "timestamped_text", "tracking", False, {}, 200),
        ("execution_accuracy", "Execution Accuracy", "boolean", "criteria", False, {}, 300),
        ("hitl_breakpoint", "HITL Breakpoint", "boolean", "governance", False, {}, 400),
        ("hitl_role_gate", "HITL Role Gate", "text", "hitl", True, {"default": "Assigned_User: Signs off on manual execution steps."}, 500),
    ],
    "Bug": [
        ("severity", "Severity", "enum", "data", True, {"options": ["Blocker", "Major", "Minor"]}, 100),
        ("environment", "Environment", "enum", "data", True, {"options": ["Production", "Staging", "Development", "Local"]}, 200),
        ("expected_behavior", "Expected Behavior", "rich_text", "data", True, {}, 300),
        ("actual_behavior", "Actual Behavior", "rich_text", "data", True, {}, 400),
        ("rca", "Root Cause Analysis", "rich_text", "tracking", False, {}, 500),
        ("resolution", "Resolution", "rich_text", "tracking", False, {}, 600),
        ("regression_criteria", "Regression Criteria", "rich_text", "criteria", False, {}, 700),
        ("agent_failure_mode", "Agent Failure Mode", "enum", "governance", False, {"options": ["Hallucination", "Logic Error", "Tool Timeout"]}, 800),
        ("hitl_role_gate", "HITL Role Gate", "text", "hitl", True, {"default": "QA_Lead: Validates Fix and Regression Suite."}, 900),
    ],
}


def seed_properties(apps, schema_editor):
    IssueType = apps.get_model("db", "IssueType")
    IssueTypeProperty = apps.get_model("db", "IssueTypeProperty")

    for issue_type in IssueType.objects.filter(is_active=True, deleted_at__isnull=True):
        type_name = issue_type.name
        if type_name not in PROPERTY_DEFINITIONS:
            continue

        for key, name, field_type, category, is_required, config, sort_order in PROPERTY_DEFINITIONS[type_name]:
            IssueTypeProperty.objects.get_or_create(
                issue_type=issue_type,
                key=key,
                deleted_at__isnull=True,
                defaults={
                    "workspace": issue_type.workspace,
                    "name": name,
                    "field_type": field_type,
                    "category": category,
                    "is_required": is_required,
                    "config": config,
                    "sort_order": sort_order,
                    "is_active": True,
                },
            )


def reverse_seed(apps, schema_editor):
    IssueTypeProperty = apps.get_model("db", "IssueTypeProperty")
    all_keys = set()
    for props in PROPERTY_DEFINITIONS.values():
        for key, *_ in props:
            all_keys.add(key)
    IssueTypeProperty.objects.filter(key__in=all_keys).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0121_issuetypeproperty_issuepropertyvalue"),
    ]

    operations = [
        migrations.RunPython(seed_properties, reverse_seed),
    ]
