# Generated by Django 4.2.28 on 2026-02-28
from django.db import migrations


# Property definitions for upper-level portfolio types: Theme (L0),
# Initiative (L1), Capability (L2).  These sit above Epic in the hierarchy
# and are created from PRD vision, roadmap phases, and functional sections.
#
# Each entry: (key, name, field_type, category, is_required, config, sort_order)
PROPERTY_DEFINITIONS = {
    "Theme": [
        ("vision", "Vision Statement", "rich_text", "data", True, {}, 100),
        ("strategic_objectives", "Strategic Objectives", "checklist", "data", True, {}, 200),
        ("time_horizon", "Time Horizon", "text", "data", False, {}, 300),
        ("target_users", "Target Users", "tags", "data", False, {}, 400),
        ("kpis", "Key Performance Indicators", "checklist", "criteria", True, {}, 500),
        ("portfolio_status", "Portfolio Status", "enum", "tracking", False,
         {"options": ["Discovery", "Planning", "Active", "Sustaining", "Sunset"]}, 600),
        ("hitl_role_gate", "HITL Role Gate", "text", "hitl", True,
         {"default": "CEO_CPO: Approves Strategic Direction and Portfolio Allocation."}, 700),
    ],
    "Initiative": [
        ("business_case", "Business Case", "rich_text", "data", True, {}, 100),
        ("target_outcome", "Target Outcome", "rich_text", "data", True, {}, 200),
        ("investment", "Investment Level", "currency", "data", False, {"currency": "USD"}, 300),
        ("sponsor", "Sponsor", "text", "data", False, {}, 400),
        ("phase", "Phase", "rich_text", "tracking", False, {}, 500),
        ("dependencies", "Dependencies", "checklist", "tracking", False, {}, 600),
        ("success_metrics", "Success Metrics", "checklist", "criteria", True, {}, 700),
        ("hitl_role_gate", "HITL Role Gate", "text", "hitl", True,
         {"default": "VP_Engineering: Approves Scope and Resource Allocation."}, 800),
    ],
    "Capability": [
        ("target_outcome", "Target Outcome", "rich_text", "data", True, {}, 100),
        ("functional_scope", "Functional Scope", "checklist", "data", True, {}, 200),
        ("architecture_impact", "Architecture Impact", "rich_text", "data", False, {}, 300),
        ("required_skills", "Required Skills", "tags", "data", False, {}, 400),
        ("technical_dependencies", "Technical Dependencies", "checklist", "tracking", False, {}, 500),
        ("readiness_criteria", "Readiness Criteria", "checklist", "criteria", True, {}, 600),
        ("hitl_role_gate", "HITL Role Gate", "text", "hitl", True,
         {"default": "Solutions_Architect: Approves Technical Feasibility and Scope."}, 700),
    ],
}


def seed_properties(apps, schema_editor):
    IssueType = apps.get_model("db", "IssueType")
    IssueTypeProperty = apps.get_model("db", "IssueTypeProperty")

    for issue_type in IssueType.objects.filter(is_active=True, deleted_at__isnull=True):
        type_name = issue_type.name
        if type_name not in PROPERTY_DEFINITIONS:
            continue

        for key, name, field_type, category, is_required, config, sort_order in PROPERTY_DEFINITIONS[type_name]:
            IssueTypeProperty.objects.get_or_create(
                issue_type=issue_type,
                key=key,
                deleted_at__isnull=True,
                defaults={
                    "workspace": issue_type.workspace,
                    "name": name,
                    "field_type": field_type,
                    "category": category,
                    "is_required": is_required,
                    "config": config,
                    "sort_order": sort_order,
                    "is_active": True,
                },
            )


def reverse_seed(apps, schema_editor):
    IssueTypeProperty = apps.get_model("db", "IssueTypeProperty")
    all_keys = set()
    for props in PROPERTY_DEFINITIONS.values():
        for key, *_ in props:
            all_keys.add(key)
    IssueTypeProperty.objects.filter(key__in=all_keys).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0122_seed_issue_type_properties"),
    ]

    operations = [
        migrations.RunPython(seed_properties, reverse_seed),
    ]
