# Generated by Django 4.2.28 on 2026-03-01
from django.db import migrations


# Shared baseline properties to add where missing.
# sort_order 50-70 places them at the TOP of their categories so they
# appear before type-specific properties.
#
# Notes (rich_text, tracking) — universal freeform notes field.
# Tags (tags, data) — lightweight labels / keywords for search & filter.
# Dependencies (checklist, tracking) — explicit dependency tracking.
#
# Mapping: type_name → list of (key, name, field_type, category, is_required, config, sort_order)

SHARED_PROPERTIES = {
    # Theme: has target_users (tags-like) but no Notes or Dependencies
    "Theme": [
        ("shared_notes", "Notes", "rich_text", "tracking", False, {}, 50),
        ("shared_dependencies", "Dependencies", "checklist", "tracking", False, {}, 70),
    ],
    # Initiative: has dependencies but no Notes or Tags
    "Initiative": [
        ("shared_notes", "Notes", "rich_text", "tracking", False, {}, 50),
        ("shared_tags", "Tags", "tags", "data", False, {}, 60),
    ],
    # Capability: has required_skills (tags) and technical_dependencies (checklist) but no Notes
    "Capability": [
        ("shared_notes", "Notes", "rich_text", "tracking", False, {}, 50),
    ],
    # Epic: missing all three
    "Epic": [
        ("shared_notes", "Notes", "rich_text", "tracking", False, {}, 50),
        ("shared_tags", "Tags", "tags", "data", False, {}, 60),
        ("shared_dependencies", "Dependencies", "checklist", "tracking", False, {}, 70),
    ],
    # Feature: has stack (tags) — needs Notes and Dependencies
    "Feature": [
        ("shared_notes", "Notes", "rich_text", "tracking", False, {}, 50),
        ("shared_dependencies", "Dependencies", "checklist", "tracking", False, {}, 70),
    ],
    # User Story: missing all three
    "User Story": [
        ("shared_notes", "Notes", "rich_text", "tracking", False, {}, 50),
        ("shared_tags", "Tags", "tags", "data", False, {}, 60),
        ("shared_dependencies", "Dependencies", "checklist", "tracking", False, {}, 70),
    ],
    # Task: missing all three
    "Task": [
        ("shared_notes", "Notes", "rich_text", "tracking", False, {}, 50),
        ("shared_tags", "Tags", "tags", "data", False, {}, 60),
        ("shared_dependencies", "Dependencies", "checklist", "tracking", False, {}, 70),
    ],
    # Sub-task: missing all three
    "Sub-task": [
        ("shared_notes", "Notes", "rich_text", "tracking", False, {}, 50),
        ("shared_tags", "Tags", "tags", "data", False, {}, 60),
        ("shared_dependencies", "Dependencies", "checklist", "tracking", False, {}, 70),
    ],
    # Bug: missing all three
    "Bug": [
        ("shared_notes", "Notes", "rich_text", "tracking", False, {}, 50),
        ("shared_tags", "Tags", "tags", "data", False, {}, 60),
        ("shared_dependencies", "Dependencies", "checklist", "tracking", False, {}, 70),
    ],
}

SHARED_KEYS = {"shared_notes", "shared_tags", "shared_dependencies"}


def seed_shared_properties(apps, schema_editor):
    IssueType = apps.get_model("db", "IssueType")
    IssueTypeProperty = apps.get_model("db", "IssueTypeProperty")

    for issue_type in IssueType.objects.filter(is_active=True, deleted_at__isnull=True):
        type_name = issue_type.name
        if type_name not in SHARED_PROPERTIES:
            continue

        for key, name, field_type, category, is_required, config, sort_order in SHARED_PROPERTIES[type_name]:
            IssueTypeProperty.objects.get_or_create(
                issue_type=issue_type,
                key=key,
                deleted_at__isnull=True,
                defaults={
                    "workspace": issue_type.workspace,
                    "name": name,
                    "field_type": field_type,
                    "category": category,
                    "is_required": is_required,
                    "config": config,
                    "sort_order": sort_order,
                    "is_active": True,
                },
            )


def reverse_seed(apps, schema_editor):
    IssueTypeProperty = apps.get_model("db", "IssueTypeProperty")
    IssueTypeProperty.objects.filter(key__in=SHARED_KEYS).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0123_seed_upper_level_properties"),
    ]

    operations = [
        migrations.RunPython(seed_shared_properties, reverse_seed),
    ]
